Repository TheRenegadeCoder/SnakeMD, pull requests merged in 2021-12, with the labels that each got.

#42 Added Nesting to Table of Contents
  setup.py
  snakemd/generator.py
  snakemd/readme.py
  tests/test_document.py
  tests/test_md_list.py
  tests/test_table_of_contents.py
Labels: enhancement

#44 Fixed Issue That Caused Linting Errors for Markdown Lists
  docsrc/version-history.rst
  setup.py
  snakemd/generator.py
  tests/test_md_list.py
  tests/test_table_of_contents.py
Labels: bug

#45 Added a Way to Create a New Document Without Importing Any Classes
  docsrc/usage.rst
  docsrc/version-history.rst
  setup.py
  snakemd/__init__.py
  snakemd/generator.py
Labels: enhancement

#46 Added Support for Read The Docs
  .readthedocs.yml
  requirements.txt
  setup.py
Labels: documentation, enhancement

#49 Added Super Linter Action to Lint Markdown
  .github/workflows/linter.yml
  README.md
  snakemd/readme.py
Labels: enhancement

#50 Added Python Matrix of Version Testing
  .github/workflows/test.yml
  setup.py
Labels: enhancement

#52 Updated Version History
  docs/version-history.rst
  setup.py
Labels: enhancement

#55 Implement a List of Checkboxes
  snakemd/generator.py
  tests/test_md_check_list.py
Labels: enhancement
